### ISSUE TITLE
[Tracking] Consider renaming "easy" label to "good first issue" and using only "help wanted" instead of "up for grabs"

### ISSUE THREAD

**Issue by mairaw** [dotnet/wpf#6937]
Using the **help wanted** label is especially recognized by GitHub and we're trying to get a consistent experience for newcomers. See context at https://github.com/dotnet/runtime/issues/71496
Your repo has the two: **help wanted** and **up for grabs**. Consider converting all the **up for grabs** issues into **help wanted**. Some people added up for grabs in the label description in other repos in case folks are looking for that label instead.

You should also consider adding the project to https://up-for-grabs.net/
See an example PR at https://github.com/up-for-grabs/up-for-grabs.net/pull/3329

/cc @danmoseley

**Comment by singhashish-wpf** [comment]
- [ ] Renamed easy to Good first Issue
- [ ] Converted up for grabs to help wanted
- [ ] Added .NET WPF project to up for grabs https://github.com/up-for-grabs/up-for-grabs.net/pull/3331

**Comment by mairaw** [comment]
Awesome! Closing the issue then.

![image](https://user-images.githubusercontent.com/12971179/186538839-1fe6a12f-4298-476b-86a3-4e8b3a8c8c9d.png)
