### ISSUE TITLE
Missing WIC features

### ISSUE THREAD

**Issue by miloush** [dotnet/wpf#7932]
Tracking issue for features that WIC has but WPF does not.

- plenty of built-in pixel formats #4570, most importantly:
    - [ ] `WICPixelFormat32bppRGBA` used by built-in WEBP #1436
    - [ ] `WICPixelFormat96bppRGBFloat` used by built-in TIFF
    - big groups of unsupported formats:
      - [ ] 10-bit
      - [ ] fixed point
      - [ ] half float
      - [ ] CMYK
      - [ ] n-channels
- [ ] support for add-in pixel formats
- enumererating available:
  - [ ] decoders and encoders #7930 
  - [ ] metadata readers and writers
  - [ ] pixel formats and converters
- classes for new or oupdated built-in codecs:
  - [ ] JPEG XR #6337
  - [ ] DDS (with its own interfaces)
  - [ ] DNG
  - [ ] HEIF (with its own metadata interfaces) #6337
  - [ ] WEBP (with its own metadata interfaces) #6337
  - [ ] recognize new PNG codec CLSIDs
  - [ ] new JPEG properties (`IWICJpegFrameDecode`, `IWICJpegFrameEncode`)
- [ ] `IWICDevelopRaw` #4567
- [ ] `IWICCodecProgressNotification`
- [ ] allow developres to add managed classes for their WIC components
- [ ] allow developers to supply non-WIC based codecs https://github.com/dotnet/wpf/issues/1436#issuecomment-562444330
  - [ ] allow developers to read and write metadata
- [ ] progressive decoding `IWICProgressiveLevelControl`

**Comment by lindexi** [comment]
@miloush Can add [Adding CreateBitmapSourceFromWICBitmap method to System.Windows.Interop.Imaging by lindexi · Pull Request #7223 · dotnet/wpf](https://github.com/dotnet/wpf/pull/7223 ) ?

**Comment by Eagle3386** [comment]
@miloush Why is only
> progressive **_decoding_** `IWICProgressiveLevelControl`

and not also **_encoding_** for JPEG files planned?
Because for PNG files, the equivalent technology (named [Interlace](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.pngbitmapencoder.interlace)) is available for de- as well as encoding.

However, there's no such `Progressive` property for the [JpegBitmapEncoder](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.jpegbitmapencoder)?! 🥺

**Comment by miloush** [comment]
As noted in #11927, WPF contains only wrappers over WIC and WIC does not implement progressive encoding for JPEG. WIC is a core Windows component, the WPF team cannot help here.

**Comment by Eagle3386** [comment]
You can't even forward this to the appropriate colleagues for them to implement it in WIC?
