### ISSUE TITLE
Epic - Support Windows 11 Look and Feel for WPF

### ISSUE THREAD

**Issue by singhashish-wpf** [dotnet/wpf#8538]
- [ ] [Branching, Building, Setup, Review and Guidelines](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111302)
- [ ] [Public API changes](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111058)
- [ ] [Control Specific Styling](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=43736038)
- [ ] [Theme Specific Styling](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111114)
- [ ] [System Theme Interactions](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111128)
- [ ] [Theme Manager and Theme Switching](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111425)
- [ ] [Snap Layout](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111134)
- [ ] [Rounded Corners](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111137)
- [ ] [Mica and Acrylic Support](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111145)
- [ ] [Visual Studio Toolbox and Designer Integration](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111162)
- [ ] [OSS Scrubbing](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111512)
- [ ] [Accessibility](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111177)
- [ ] [Compatibility](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111203)
- [ ] [Fallback/opt-out Mechanism](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111223)
- [ ] [Sample Applications](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111236)
- [ ] [Testing](https://github.com/orgs/dotnet/projects/147/views/1?pane=issue&itemId=45111252)
