### ISSUE TITLE
Win11 Theming outstanding Issue Tracker

### ISSUE THREAD

**Issue by dipeshmsft** [dotnet/wpf#8991]
### Description

This issue tracks the review comments mentioned in #8870 : 

- [ ] Use ThemeGenerator to combine all the merged dictionaries ( https://github.com/dotnet/wpf/pull/8870#discussion_r1524158549 )
- [ ] Enhance accent color management ( https://github.com/dotnet/wpf/pull/8870#discussion_r1524771043 , https://github.com/dotnet/wpf/pull/8870#discussion_r1525831435 )
- [ ] Undo TextEditorContextMenu, DataGridCheckBoxColumn, Window SetResourceReference workarounds ( https://github.com/dotnet/wpf/pull/8870#discussion_r1526098439 )
- [ ] Replace OS version checks with calls to OSVersionHelper ( https://github.com/dotnet/wpf/pull/8870#discussion_r1526088511 )
- [ ] Document introducing dependency on fonts present in Win11 only ( https://github.com/dotnet/wpf/pull/8870#discussion_r1525128672 )
- [ ] Handling WindowBackdrop in OnSourceInitialized ( https://github.com/dotnet/wpf/pull/8870#discussion_r1539763302 )
- [ ] Remove dependency on Application.Current ( https://github.com/dotnet/wpf/pull/8870#discussion_r1539943016 )
- [ ] Enabling glass frame causes client area and caption button overlap. ( https://github.com/dotnet/wpf/pull/8870#discussion_r1545270901 )
- [ ] Access keys are not respected and rendered as character

The issues related to control styles ( XAML and resources ) will be tracked separately.

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by robloo** [comment]
I see at least two more critical ones:

 * Key names
    * https://github.com/dotnet/wpf/pull/8870#discussion_r1562619789
    * https://github.com/dotnet/wpf/pull/8870#discussion_r1562634445
 * Hardcoded font family names
    * https://github.com/dotnet/wpf/pull/8870#issuecomment-2053688794

As noted a deep comparison with and understanding of upstream WinUI source is really needed.

**Comment by dipeshmsft** [comment]
@robert-abeo, thanks for the point out, actually most of them were already merged in main. We will keep fixing these issues in styles as they come in, but currently our main priority with Fluent theme is to provide a way to make it default. I have been figuring out a way to allow users to access colors and brush resources defined in Fluent style and following that, we would like to get the theme switch API working. 

Since you have been actively involved in discussions for the theming changes, I would like to know your inputs on #8932

**Comment by dipeshmsft** [comment]
Thanks @robert-abeo , I am going through the comments of last night. The PR you mentioned is reviewed, but depending on the direction we are going, this may need a bit of change, that's why it's still open. Rest assured, we will get to the close of this PR by Preview 7.

**Comment by dipeshmsft** [comment]
@robert-abeo 

> The PR I'm looking at specifically with the highest priority is: https://github.com/dotnet/wpf/pull/9171. There are a number of controls currently missing Fluent styles. There are a few other nice-to-have bug fixes as well.

I think there is a misunderstanding here, the styles mentioned here are not Fluent styled. The styles here are basically copies of Aero2 styles. The ones not marked "Additional styling not needed" are basically the same in Fluent and Aero2, rest of them still needs to be styled.

**Comment by dipeshmsft** [comment]
> Ok, my mistake. Thanks for the clarification. I knew these were Aero2 based styles but I thought they were updated to use Fluent resources where needed.

We are getting to this.

**Comment by lindexi** [comment]
Reference: https://github.com/dotnet/wpf/issues/10077

**Comment by dipeshmsft** [comment]
Adding the following issue related to discussion of default behavior of TextBox in regard to delete button here : https://github.com/dotnet/wpf/issues/10180

**Comment by dipeshmsft** [comment]
@robert-abeo, thanks for your feedback here, I was just in the line to open a discussion post to seek everyones input on how we are going to work on rest of the issues - like missing styles, fluent bug fixes, testing etc. Please wait for a day or two and we will have the post up.

**Comment by dipeshmsft** [comment]
@robert-abeo, we have posted a Discussion Post as I mentioned above on what we are planning to do in Fluent going forward : https://github.com/dotnet/wpf/discussions/10387
